FAQ #3
NCAR/xdev pull request #123
Opened 2020-11-18 22:29 UTC by jukent

2020-11-19 18:49 UTC, kmpaul requested changes
These are just minor suggestions, mostly formatting for clarity.  It looks great, @jukent!

2020-11-19 18:49 UTC, kmpaul commented on site/posts/python-tutorial-faq-part-3.ipynb
> +    "**Q.** Are the spaces necessary around operators or  after commas?\n",
```suggestion
    "**Q.** Are the spaces necessary around operators or after commas?\n",
```

2020-11-19 18:49 UTC, kmpaul commented on site/posts/python-tutorial-faq-part-3.ipynb
> +    "**A.** If you don’t want to return anything you don’t need to have a return statement at the end of your function. By default, that means the function will return None.\n",
```suggestion
    "**A.** If you don’t want to return anything you don’t need to have a `return` statement at the end of your function. By default, that means the function will return `None`.\n",
```

2020-11-19 18:49 UTC, kmpaul commented on site/posts/python-tutorial-faq-part-3.ipynb
> +    "**Q.** In the `f-string` formatting, is `f` a function here?\n",
```suggestion
    "**Q.** In the `f-string` formatting (i.e., `f'string'`), is `f` a function here?\n",
```

2020-11-19 18:49 UTC, kmpaul commented on site/posts/python-tutorial-faq-part-3.ipynb
> +    "**A.** They are defined in the for loop and are returned from the zip function when it is iterated over.\n",
```suggestion
    "**A.** They are defined in the `for` loop and are returned from the `zip` function when it is iterated over.\n",
```

2020-11-19 19:18 UTC, jukent commented
> These are just minor suggestions, mostly formatting for clarity. It looks great, @jukent!

Thanks for the edits!

2020-11-20 22:59 UTC, halehawk commented
Do you need to mention in Python 3, the first question will get 2/2=1.0, but in Python 2, 2/2=1
In f string question, you have 2 would, please remove one.

2020-11-21 18:43 UTC, kmpaul commented
That's a good point @halehawk. Maybe a mention that Python 2 is different, but that we don't recommend using Python 2 because it is deprecated.

2020-11-23 20:27 UTC, kmpaul requested changes
Here's a first draft of some language regarding Python 2.

2020-11-23 20:27 UTC, kmpaul commented on site/posts/python-tutorial-faq-part-3.ipynb
> +    "**A.** The numeric type is inferred. `/` always returns a float for numeric types. `//` always returns an integer.\n",
```suggestion
    "**A.** The numeric type is inferred. `/` always returns a float for numeric types. `//` always returns an integer. 
 One should note that Python 2 does not behave this way.  In Python 2, the `//` operator does not exist and the `/` operator behaves like it does in other languages (i.e., division of two integers yields an integer and division with a float yields a float).\n",
```

2020-11-23 21:35 UTC, jukent commented
> Here's a first draft of some language regarding Python 2.

I think this answers the Python 2 nuance thoroughly enough for our audience.

2020-11-23 22:32 UTC, kmpaul approved these changes

2020-11-23 22:32 UTC, merged