FAQ from "Your First Package"
NCAR/xdev pull request #131
Opened 2021-02-20 00:07 UTC by jukent

2021-02-24 23:29 UTC, jukent commented
Can I merge this if there are no reviews by the end of tomorrow @NCAR/xdev-education ?

2021-02-25 21:35 UTC, kmpaul requested changes
Remove timezone info in calendar

2021-02-25 21:35 UTC, kmpaul commented on site/posts/python-tutorial-seminar-series-spring-2021.ipynb
> +    "<iframe src=\"https://calendar.google.com/calendar/embed?src=c_krmtmqm6kb5u7ke6t5on9l0rus%40group.calendar.google.com&ctz=America%2FDenver\" style=\"border: 0\" width=\"800\" height=\"600\" fram
```suggestion
    "<iframe src=\"https://calendar.google.com/calendar/embed?src=c_krmtmqm6kb5u7ke6t5on9l0rus%40group.calendar.google.com\" style=\"border: 0\" width=\"800\" height=\"600\" frameborder=\"0\" scrolling=\"no\"></iframe>"
```

2021-02-25 21:47 UTC, kmpaul approved these changes
Thanks, @jukent!

2021-02-25 21:50 UTC, merged