add jupyter faq
NCAR/xdev pull request #137
Opened 2021-03-03 20:02 UTC by jukent

2021-03-03 20:25 UTC, kmpaul requested changes
Just a few modifications, but I think it looks good.

2021-03-03 20:25 UTC, kmpaul commented on site/posts/jupyter-notebooks-faq.ipynb
> +    "**A.** If you don’t want to use your default browser (which Jupyter will automatically open with), you can specify a different one with `jupyter lab —browser=chrome` \n",
```suggestion
    "**A.** If you don’t want to use your default browser (which Jupyter will automatically open), you can specify a different one with `jupyter lab —browser=chrome` (e.g., for Chrome)\n",
```

2021-03-03 20:25 UTC, kmpaul commented on site/posts/jupyter-notebooks-faq.ipynb
> +  },
I would delete this question.  It does not have enough specificity to be useful, and the answer reflects that.

```suggestion
```

2021-03-03 20:25 UTC, kmpaul commented on site/posts/jupyter-notebooks-faq.ipynb
> +    "**Q.** Does Jupyter lab care about being shut down gracefully?  If I you just `ctrl-C` it from the command-line, does that do anything bad?\n",
```suggestion
    "**Q.** Does Jupyter Lab care about being shut down gracefully?  If I you just `ctrl-C` it from the command-line, does that do anything bad?\n",
```

2021-03-03 20:25 UTC, kmpaul commented on site/posts/jupyter-notebooks-faq.ipynb
> +  },
This is also not a specific question.  The real answer is "watch the video," but that's also not helpful.  If a person asks this question before actually seeing the video, then the answer is "Wait for it!"  And if they have seen the video and ask this question, then the answer is "It's your preference."

```suggestion
```

2021-03-03 20:25 UTC, kmpaul commented on site/posts/jupyter-notebooks-faq.ipynb
> +    "**A.** Running code uses resources, different environments use disc space. It is possible to have a ton of duplication (every single user of the virtual environment has installed `numpy`) but th
```suggestion
    "**A.** Running code uses resources, different environments use disc space. It is possible to have a ton of duplication (e.g., every single user of the virtual environment has installed `numpy`) but this gives you a lot of control over your own software versioning. You can prune unused virtual environments to save disc space with the command `conda env remove —name my_env`, or try `conda clean -a` to clean up any cached downloaded packages.\n",
```

2021-03-03 20:25 UTC, kmpaul commented on site/posts/jupyter-notebooks-faq.ipynb
> +    "**Q.** Why do we install miniconda instead of anaconda?\n",
```suggestion
    "**Q.** Why do we install Miniconda instead of Anaconda?\n",
```

2021-03-03 20:25 UTC, kmpaul commented on site/posts/jupyter-notebooks-faq.ipynb
> +    "**A.** Miniconda is much more lightweight than anaconda. It contains fewer packages and takes up less disc space.\n",
```suggestion
    "**A.** Miniconda is much more lightweight than Anaconda. It contains fewer packages and takes up less disc space.\n",
```

2021-03-03 20:40 UTC, jukent commented
> Just a few modifications, but I think it looks good.

Thanks Kevin!

2021-03-03 23:33 UTC, kmpaul approved these changes
Looks good.

2021-03-03 23:50 UTC, merged

2021-03-04 16:02 UTC, sherimickelson commented on site/posts/jupyter-notebooks-faq.ipynb
> +    "-----"
Depending how users shut things down, it could still be running in the background.  Should we include something on `jupyter notebook list`?

2021-03-04 17:13 UTC, jukent commented on site/posts/jupyter-notebooks-faq.ipynb
> +    "-----"
Good point Sheri! I addressed this in #139